import { Scan, NetworkScan, WebScan, CVE, Agent, VulnerabilityStats, OpenPort } from './types'


export const webPipelineSteps = [
  {
    id: 'targeting',
    label: 'Target Initialization',
    detail: 'Validate target and prepare scan context',
    icon: '◎',
  },
  {
    id: 'spidering',
    label: 'Spider Crawl',
    detail: 'Discover URLs, forms, and parameters',
    icon: '🕷️',
  },
  {
    id: 'fingerprinting',
    label: 'Fingerprinting',
    detail: 'Detect headers, server tech, and configs',
    icon: '⌘',
  },
  {
    id: 'risk',
    label: 'Risk Analysis',
    detail: 'Score findings by severity and confidence',
    icon: '⚠',
  },
  {
    id: 'reporting',
    label: 'Report Generation',
    detail: 'Prepare findings and exportable report',
    icon: '📄',
  },
]

export const owaspTop10 = [
  { id: 'A01', name: 'Broken Access Control', checked: true },
  { id: 'A02', name: 'Cryptographic Failures', checked: true },
  { id: 'A03', name: 'Injection', checked: true },
  { id: 'A04', name: 'Insecure Design', checked: true },
  { id: 'A05', name: 'Security Misconfiguration', checked: true },
  { id: 'A06', name: 'Vulnerable and Outdated Components', checked: true },
  { id: 'A07', name: 'Identification and Authentication Failures', checked: true },
  { id: 'A08', name: 'Software and Data Integrity Failures', checked: true },
  { id: 'A09', name: 'Security Logging and Monitoring Failures', checked: true },
  { id: 'A10', name: 'Server-Side Request Forgery', checked: true },
]

export const webVulns = [
  {
    id: 'wv-1',
    name: 'SQL Injection',
    risk: 'critical',
    cwe: 'CWE-89',
    confidence: 'high',
    method: 'GET',
    url: '/login',
    parameter: 'username',
    evidence: "Database error pattern detected near ' OR 1=1 --",
    owaspCategory: 'A03: Injection',
  },
  {
    id: 'wv-2',
    name: 'Reflected XSS',
    risk: 'high',
    cwe: 'CWE-79',
    confidence: 'high',
    method: 'GET',
    url: '/search',
    parameter: 'q',
    evidence: 'Injected payload reflected unsanitized in HTML response',
    owaspCategory: 'A03: Injection',
  },
  {
    id: 'wv-3',
    name: 'Missing HSTS Header',
    risk: 'medium',
    cwe: 'CWE-693',
    confidence: 'medium',
    method: 'GET',
    url: '/',
    parameter: '',
    evidence: 'Strict-Transport-Security header not present',
    owaspCategory: 'A05: Security Misconfiguration',
  },
  {
    id: 'wv-4',
    name: 'Server Banner Disclosure',
    risk: 'low',
    cwe: 'CWE-200',
    confidence: 'high',
    method: 'GET',
    url: '/',
    parameter: '',
    evidence: 'Server header reveals Apache/2.4.52',
    owaspCategory: 'A05: Security Misconfiguration',
  },
  {
    id: 'wv-5',
    name: 'Unauthenticated Admin Access',
    risk: 'high',
    cwe: 'CWE-306',
    confidence: 'high',
    method: 'GET',
    url: '/admin/users',
    parameter: '',
    evidence: 'Protected admin resource accessible without login',
    owaspCategory: 'A01: Broken Access Control',
  },
  {
    id: 'wv-6',
    name: 'Weak Session Cookie Settings',
    risk: 'medium',
    cwe: 'CWE-614',
    confidence: 'medium',
    method: 'GET',
    url: '/session',
    parameter: '',
    evidence: 'Session cookie missing Secure and HttpOnly flags',
    owaspCategory: 'A07: Identification and Authentication Failures',
  },
  {
    id: 'wv-7',
    name: 'Outdated JavaScript Library',
    risk: 'medium',
    cwe: 'CWE-1104',
    confidence: 'medium',
    method: 'GET',
    url: '/static/jquery.js',
    parameter: '',
    evidence: 'Detected outdated jQuery version with known issues',
    owaspCategory: 'A06: Vulnerable and Outdated Components',
  },
  {
    id: 'wv-8',
    name: 'Directory Listing Enabled',
    risk: 'low',
    cwe: 'CWE-548',
    confidence: 'medium',
    method: 'GET',
    url: '/assets/',
    parameter: '',
    evidence: 'Directory index exposed to unauthenticated users',
    owaspCategory: 'A05: Security Misconfiguration',
  },
  {
    id: 'wv-9',
    name: 'Sensitive Endpoint Exposure',
    risk: 'high',
    cwe: 'CWE-200',
    confidence: 'high',
    method: 'GET',
    url: '/api/user/1',
    parameter: '',
    evidence: 'PII returned without sufficient authorization checks',
    owaspCategory: 'A01: Broken Access Control',
  },
  {
    id: 'wv-10',
    name: 'Webhook SSRF Risk',
    risk: 'medium',
    cwe: 'CWE-918',
    confidence: 'medium',
    method: 'POST',
    url: '/api/webhook',
    parameter: 'url',
    evidence: 'External URL fetch behavior may allow internal resource access',
    owaspCategory: 'A10: Server-Side Request Forgery',
  },
]
export const adminUser = {
  id: 'admin-1',
  username: 'admin',
  email: 'admin@securex.pro',
  role: 'admin' as const,
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=admin',
  lastLogin: new Date(),
}

export const agentUser = {
  id: 'agent-1',
  username: 'security-agent-01',
  email: 'agent@securex.pro',
  role: 'agent' as const,
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=agent',
  lastLogin: new Date(),
}

// Common CVEs for realistic data
const commonCVEs: CVE[] = [
  {
    id: 'cve-1',
    cveName: 'CVE-2024-1234',
    description: 'Critical SQL Injection vulnerability in authentication module',
    severity: 'critical',
    cvssScore: 9.8,
    cweId: 'CWE-89',
    cweName: 'SQL Injection',
    publicationDate: new Date('2024-01-15'),
    exploitCount: 15,
    exploits: [
      { id: 'e1', msf_id: 'exploit/multi/sqli_auth', title: 'SQL Injection Authentication Bypass', type: 'web', reliability: 'excellent' },
      { id: 'e2', msf_id: 'exploit/multi/sqli_extract', title: 'SQL Injection Data Extraction', type: 'web', reliability: 'good' },
    ],
    remediation: 'Update to version 2.5.0 or later, implement parameterized queries',
  },
  {
    id: 'cve-2',
    cveName: 'CVE-2024-5678',
    description: 'Remote Code Execution in file upload handler',
    severity: 'critical',
    cvssScore: 9.6,
    cweId: 'CWE-434',
    cweName: 'Unrestricted Upload of File with Dangerous Type',
    publicationDate: new Date('2024-02-01'),
    exploitCount: 8,
    exploits: [
      { id: 'e3', msf_id: 'exploit/multi/rce_upload', title: 'File Upload RCE', type: 'web', reliability: 'excellent' },
    ],
    remediation: 'Implement file type validation, store uploads outside webroot',
  },
  {
    id: 'cve-3',
    cveName: 'CVE-2024-9999',
    description: 'Cross-Site Scripting (XSS) in user profile pages',
    severity: 'high',
    cvssScore: 7.2,
    cweId: 'CWE-79',
    cweName: 'Improper Neutralization of Input During Web Page Generation',
    publicationDate: new Date('2024-01-20'),
    exploitCount: 12,
    exploits: [
      { id: 'e4', msf_id: 'exploit/multi/xss_cookie_steal', title: 'XSS Cookie Stealing', type: 'web', reliability: 'good' },
    ],
    remediation: 'Implement input validation and output encoding',
  },
  {
    id: 'cve-4',
    cveName: 'CVE-2023-4455',
    description: 'Buffer Overflow in network service',
    severity: 'high',
    cvssScore: 8.1,
    cweId: 'CWE-120',
    cweName: 'Buffer Copy without Checking Size of Input',
    publicationDate: new Date('2023-12-10'),
    exploitCount: 5,
    exploits: [
      { id: 'e5', msf_id: 'exploit/windows/smb_buffer_overflow', title: 'SMB Buffer Overflow', type: 'network', reliability: 'average' },
    ],
    remediation: 'Update to patched version',
  },
  {
    id: 'cve-5',
    cveName: 'CVE-2024-7777',
    description: 'Broken Authentication in API endpoints',
    severity: 'high',
    cvssScore: 7.5,
    cweId: 'CWE-287',
    cweName: 'Improper Authentication',
    publicationDate: new Date('2024-02-15'),
    exploitCount: 6,
    exploits: [],
    remediation: 'Implement OAuth 2.0 or JWT properly',
  },
]

// Network Scans
export const networkScans: NetworkScan[] = [
  {
    id: 'scan-net-1',
    type: 'network',
    name: 'Internal Network Baseline Scan',
    target: '192.168.1.0/24',
    ipRange: '192.168.1.0/24',
    portRange: '1-65535',
    intensity: 'thorough',
    status: 'completed',
    severity: 'critical',
    riskScore: 92,
    startedAt: new Date('2024-04-10T14:30:00'),
    completedAt: new Date('2024-04-10T18:45:00'),
    vulnerabilityCount: 23,
    agentId: 'agent-1',
    openPorts: [
      {
        port: 22,
        protocol: 'tcp',
        service: 'ssh',
        state: 'open',
        cves: [commonCVEs[3]],
      },
      {
        port: 80,
        protocol: 'tcp',
        service: 'http',
        state: 'open',
        cves: [commonCVEs[0], commonCVEs[1], commonCVEs[2]],
      },
      {
        port: 443,
        protocol: 'tcp',
        service: 'https',
        state: 'open',
        cves: [commonCVEs[2]],
      },
      {
        port: 3306,
        protocol: 'tcp',
        service: 'mysql',
        state: 'open',
        cves: [commonCVEs[0]],
      },
    ],
  },
  {
    id: 'scan-net-2',
    type: 'network',
    name: 'DMZ Network Assessment',
    target: '10.0.1.0/24',
    ipRange: '10.0.1.0/24',
    portRange: '1-10000',
    intensity: 'normal',
    status: 'running',
    severity: 'high',
    riskScore: 78,
    startedAt: new Date('2024-04-14T09:00:00'),
    vulnerabilityCount: 17,
    agentId: 'agent-2',
    openPorts: [],
  },
  {
    id: 'scan-net-3',
    type: 'network',
    name: 'External IP Space Recon',
    target: '203.0.113.0/24',
    ipRange: '203.0.113.0/24',
    portRange: '1-1000',
    intensity: 'fast',
    status: 'completed',
    severity: 'medium',
    riskScore: 45,
    startedAt: new Date('2024-04-09T20:00:00'),
    completedAt: new Date('2024-04-09T21:30:00'),
    vulnerabilityCount: 8,
    agentId: 'agent-1',
    openPorts: [
      {
        port: 80,
        protocol: 'tcp',
        service: 'http',
        state: 'open',
        cves: [commonCVEs[1]],
      },
      {
        port: 443,
        protocol: 'tcp',
        service: 'https',
        state: 'open',
        cves: [],
      },
    ],
  },
]

// Web Scans
export const webScans: WebScan[] = [
  {
    id: 'scan-web-1',
    type: 'web',
    name: 'E-Commerce Platform Audit',
    target: 'https://example-shop.com',
    url: 'https://example-shop.com',
    scanType: 'active',
    status: 'completed',
    severity: 'critical',
    riskScore: 88,
    startedAt: new Date('2024-04-12T10:00:00'),
    completedAt: new Date('2024-04-12T12:00:00'),
    vulnerabilityCount: 19,
    agentId: 'agent-1',
    findings: [
      {
        id: 'finding-1',
        title: 'SQL Injection in Search Parameters',
        cwe: 'CWE-89',
        owasp: ['A1:2021-Broken Access Control', 'A3:2021-Injection'],
        severity: 'critical',
        description: 'The search function accepts unsanitized input allowing SQL injection attacks',
        remediation: 'Use prepared statements and parameterized queries',
        url: 'https://example-shop.com/search',
        parameter: 'q',
      },
      {
        id: 'finding-2',
        title: 'Stored XSS in Product Reviews',
        cwe: 'CWE-79',
        owasp: ['A7:2021-Cross-Site Scripting'],
        severity: 'high',
        description: 'User reviews are not properly sanitized before display',
        remediation: 'Implement output encoding and input validation',
        url: 'https://example-shop.com/products',
        parameter: 'review',
      },
      {
        id: 'finding-3',
        title: 'Weak Session Management',
        cwe: 'CWE-384',
        owasp: ['A2:2021-Cryptographic Failures'],
        severity: 'high',
        description: 'Session tokens are predictable and not properly validated',
        remediation: 'Use cryptographically strong session identifiers',
        url: '/session-management',
      },
    ],
  },
  {
    id: 'scan-web-2',
    type: 'web',
    name: 'API Security Assessment',
    target: 'https://api.example.com',
    url: 'https://api.example.com',
    scanType: 'passive',
    status: 'running',
    severity: 'high',
    riskScore: 71,
    startedAt: new Date('2024-04-14T08:30:00'),
    vulnerabilityCount: 12,
    agentId: 'agent-2',
    findings: [],
  },
  {
    id: 'scan-web-3',
    type: 'web',
    name: 'Admin Portal Penetration Test',
    target: 'https://admin.example.com',
    url: 'https://admin.example.com',
    scanType: 'active',
    status: 'completed',
    severity: 'high',
    riskScore: 82,
    startedAt: new Date('2024-04-08T14:00:00'),
    completedAt: new Date('2024-04-08T16:30:00'),
    vulnerabilityCount: 15,
    agentId: 'agent-1',
    findings: [],
  },
]

// Agents
export const agents: Agent[] = [
  {
    id: 'agent-1',
    name: 'Scanner-Alpha',
    hostname: 'scanner-01.local',
    status: 'online',
    version: '2.4.1',
    lastCheckin: new Date(),
    scansCompleted: 156,
    osType: 'linux',
    ipAddress: '192.168.1.100',
  },
  {
    id: 'agent-2',
    name: 'Scanner-Beta',
    hostname: 'scanner-02.local',
    status: 'online',
    version: '2.4.1',
    lastCheckin: new Date(Date.now() - 2 * 60000),
    scansCompleted: 89,
    osType: 'linux',
    ipAddress: '192.168.1.101',
  },
  {
    id: 'agent-3',
    name: 'Scanner-Gamma',
    hostname: 'scanner-03.local',
    status: 'offline',
    version: '2.3.5',
    lastCheckin: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    scansCompleted: 45,
    osType: 'windows',
    ipAddress: '192.168.1.102',
  },
  {
    id: 'agent-4',
    name: 'Scanner-Delta',
    hostname: 'scanner-04.local',
    status: 'scanning',
    version: '2.4.1',
    lastCheckin: new Date(Date.now() - 30000),
    scansCompleted: 203,
    osType: 'linux',
    ipAddress: '192.168.1.103',
  },
]

// Vulnerability Statistics
export const vulnerabilityStats: VulnerabilityStats = {
  critical: 12,
  high: 34,
  medium: 67,
  low: 123,
  info: 234,
}

// Helper function to get all scans
export const getAllScans = (): Scan[] => {
  return [...networkScans, ...webScans]
}

// Helper function to get vulnerability trends
export const getVulnerabilityTrends = () => {
  return [
    { month: 'Jan', critical: 5, high: 12, medium: 28, low: 45 },
    { month: 'Feb', critical: 8, high: 18, medium: 35, low: 52 },
    { month: 'Mar', critical: 6, high: 14, medium: 42, low: 61 },
    { month: 'Apr', critical: 12, high: 34, medium: 67, low: 123 },
  ]
}

// Helper function to get scan distribution
export const getScanDistribution = () => {
  return [
    { name: 'Network Scans', value: networkScans.length, fill: '#00ff88' },
    { name: 'Web Scans', value: webScans.length, fill: '#00d4ff' },
  ]
}

// Activity feed data
export const activityFeed = [
  {
    id: 'activity-1',
    type: 'scan_completed',
    title: 'Network scan completed',
    description: 'Internal Network Baseline Scan finished with 23 vulnerabilities',
    timestamp: new Date(),
    severity: 'critical',
  },
  {
    id: 'activity-2',
    type: 'agent_status',
    title: 'Agent went offline',
    description: 'Scanner-Gamma is offline',
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    severity: 'high',
  },
  {
    id: 'activity-3',
    type: 'vulnerability_found',
    title: 'Critical vulnerability discovered',
    description: 'CVE-2024-1234 found in API endpoint',
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000),
    severity: 'critical',
  },
  {
    id: 'activity-4',
    type: 'scan_started',
    title: 'New scan initiated',
    description: 'DMZ Network Assessment started',
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000),
    severity: 'info',
  },
]
